# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'G-KQ6SQ3H3YP'

menu:
- {name: 'Blog',      url: ''}
- {name: 'About',     url: 'about'}
- {name: 'Dev Info',   url: 'devinfo'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
#- {icon: 'twitter',    link: 'https://twitter.com/paululele'}
#- {icon: 'facebook',   link: 'https://www.facebook.com/paululele'}
#- {icon: 'instagram',  link: 'https://instagram.com/paululele'}
- {icon: 'github',      link: 'https://github.com/jbetz34'}
- {icon: 'linkedin',    link: 'https://linkedin.com/in/james-betz'}
- {icon: 'envelope',    link: 'mailto:jbetz34@gmail.com'}
#- {icon: 'rss-square',  link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
